### ISSUE TITLE
エンチャント台でエンチャントしたものが受け取れない 

### ISSUE THREAD

**Issue by meu32ki** [meu32ki/GenisysPro#33]
発見者 なぞ

**Comment by wakame0731** [comment]
経験値の概念をなくすのでは必要ないのでは？

**Comment by meu32ki** [comment]
確かにそうだ エンチャ台がいらないのか……

**Comment by wakame0731** [comment]
Genisys.ymlのenable-enchanting-table:をfalseにすればエンチャント台のGUIが開けなくなるはずです。(要確認)

**Comment by wakame0731** [comment]
上記の通りに設定すればエンチャント台のGUIが開けなくなることを確認しました。
