### ISSUE TITLE
きのこブロック(赤、茶両方)が石斧で破壊できない

### ISSUE THREAD

**Issue by meu32ki** [meu32ki/GenisysPro#41]
意見 破壊速度早すぎるから？
getHardnessのあたりもしくは、getResistanceもしくはtoolsの記入が行われていない？

**Comment by wakame0731** [comment]
現状壊すことはできた。ただ、斧での破壊速度は反映されない。 そのためクライアントとサーバー側で見た目の破壊判定がおかしくなってる。

_Sent from my KDDI SOV33 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
